// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_houseScreen_screen_init(void)
{
    ui_houseScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_houseScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_houseScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_houseScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_houseScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_houseScreen, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_houseScreen);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 800);
    lv_obj_set_height(ui_Container11, 480);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftsideContain2 = lv_obj_create(ui_Container11);
    lv_obj_remove_style_all(ui_leftsideContain2);
    lv_obj_set_width(ui_leftsideContain2, 60);
    lv_obj_set_height(ui_leftsideContain2, 430);
    lv_obj_set_x(ui_leftsideContain2, -370);
    lv_obj_set_y(ui_leftsideContain2, 25);
    lv_obj_set_align(ui_leftsideContain2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leftsideContain2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leftsideContain2, lv_color_hex(0x080404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftsideContain2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_leftsideContain2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_leftsideContain2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_leftsideContain2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainFunBut1 = lv_imgbtn_create(ui_leftsideContain2);
    lv_imgbtn_set_src(ui_mainFunBut1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_mainfunct_png, NULL);
    lv_imgbtn_set_src(ui_mainFunBut1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_mainfunct_png, NULL);
    lv_imgbtn_set_src(ui_mainFunBut1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_mainFunBut1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_mainFunBut1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_mainFunBut1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_mainFunBut1, 35);
    lv_obj_set_width(ui_mainFunBut1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_mainFunBut1, 0);
    lv_obj_set_y(ui_mainFunBut1, -170);
    lv_obj_set_align(ui_mainFunBut1, LV_ALIGN_CENTER);

    ui_houseFunBut1 = lv_imgbtn_create(ui_leftsideContain2);
    lv_imgbtn_set_src(ui_houseFunBut1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
    lv_imgbtn_set_src(ui_houseFunBut1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_png, NULL);
    lv_imgbtn_set_src(ui_houseFunBut1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_houseFunBut1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_houseFunBut1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_houseFunBut1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_houseFunBut1, 35);
    lv_obj_set_width(ui_houseFunBut1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_houseFunBut1, 0);
    lv_obj_set_y(ui_houseFunBut1, -110);
    lv_obj_set_align(ui_houseFunBut1, LV_ALIGN_CENTER);

    ui_tipsFunBut1 = lv_imgbtn_create(ui_leftsideContain2);
    lv_imgbtn_set_src(ui_tipsFunBut1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_video_png, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_video_png, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_tipsFunBut1, 35);
    lv_obj_set_width(ui_tipsFunBut1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_tipsFunBut1, 0);
    lv_obj_set_y(ui_tipsFunBut1, 10);
    lv_obj_set_align(ui_tipsFunBut1, LV_ALIGN_CENTER);

    ui_musicrFunBut1 = lv_imgbtn_create(ui_leftsideContain2);
    lv_imgbtn_set_src(ui_musicrFunBut1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_music2_png, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_music2_png, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_musicrFunBut1, 35);
    lv_obj_set_width(ui_musicrFunBut1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_musicrFunBut1, 0);
    lv_obj_set_y(ui_musicrFunBut1, -50);
    lv_obj_set_align(ui_musicrFunBut1, LV_ALIGN_CENTER);

    ui_Panel10 = lv_obj_create(ui_leftsideContain2);
    lv_obj_set_width(ui_Panel10, 50);
    lv_obj_set_height(ui_Panel10, 50);
    lv_obj_set_x(ui_Panel10, 0);
    lv_obj_set_y(ui_Panel10, 174);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x080404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x17A5E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sumspeakButt2 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_sumspeakButt2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_speak_png, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_speak_png, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_sumspeakButt2, 31);
    lv_obj_set_width(ui_sumspeakButt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_sumspeakButt2, -1);
    lv_obj_set_y(ui_sumspeakButt2, 0);
    lv_obj_set_align(ui_sumspeakButt2, LV_ALIGN_CENTER);

    ui_upsideContain2 = lv_obj_create(ui_Container11);
    lv_obj_remove_style_all(ui_upsideContain2);
    lv_obj_set_width(ui_upsideContain2, 740);
    lv_obj_set_height(ui_upsideContain2, 50);
    lv_obj_set_x(ui_upsideContain2, 29);
    lv_obj_set_y(ui_upsideContain2, -213);
    lv_obj_set_align(ui_upsideContain2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_upsideContain2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_upsideContain2, lv_color_hex(0x030000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_upsideContain2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_upsideContain2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_upsideContain2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_upsideContain2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_signImage2 = lv_img_create(ui_upsideContain2);
    lv_img_set_src(ui_signImage2, &ui_img_jarvis3_png);
    lv_obj_set_width(ui_signImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_signImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_signImage2, -38);
    lv_obj_set_y(ui_signImage2, 1);
    lv_obj_set_align(ui_signImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_signImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_signImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rightContain1 = lv_obj_create(ui_upsideContain2);
    lv_obj_remove_style_all(ui_rightContain1);
    lv_obj_set_width(ui_rightContain1, 100);
    lv_obj_set_height(ui_rightContain1, 44);
    lv_obj_set_x(ui_rightContain1, 252);
    lv_obj_set_y(ui_rightContain1, 1);
    lv_obj_set_align(ui_rightContain1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rightContain1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time2 = lv_label_create(ui_rightContain1);
    lv_obj_set_width(ui_time2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time2, 24);
    lv_obj_set_y(ui_time2, 1);
    lv_obj_set_align(ui_time2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time2, "15:30:56");
    lv_obj_set_style_text_color(ui_time2, lv_color_hex(0xE1E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeImage2 = lv_img_create(ui_rightContain1);
    lv_img_set_src(ui_timeImage2, &ui_img_time_png);
    lv_obj_set_width(ui_timeImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeImage2, -22);
    lv_obj_set_y(ui_timeImage2, 0);
    lv_obj_set_align(ui_timeImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_timeImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiImage2 = lv_img_create(ui_upsideContain2);
    lv_img_set_src(ui_wifiImage2, &ui_img_wifi__png);
    lv_obj_set_width(ui_wifiImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiImage2, 333);
    lv_obj_set_y(ui_wifiImage2, 0);
    lv_obj_set_align(ui_wifiImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sideContain1 = lv_obj_create(ui_Container11);
    lv_obj_remove_style_all(ui_sideContain1);
    lv_obj_set_width(ui_sideContain1, 60);
    lv_obj_set_height(ui_sideContain1, 50);
    lv_obj_set_x(ui_sideContain1, -370);
    lv_obj_set_y(ui_sideContain1, -213);
    lv_obj_set_align(ui_sideContain1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sideContain1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sideContain1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sideContain1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sideContain1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sideContain1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sideContain1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_closeImgButton2 = lv_imgbtn_create(ui_sideContain1);
    lv_imgbtn_set_src(ui_closeImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_shutdown_png, NULL);
    lv_imgbtn_set_src(ui_closeImgButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_shutdown_png, NULL);
    lv_imgbtn_set_src(ui_closeImgButton2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_closeImgButton2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_closeImgButton2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_closeImgButton2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_closeImgButton2, 34);
    lv_obj_set_width(ui_closeImgButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_closeImgButton2, LV_ALIGN_CENTER);

    ui_envirContain = lv_obj_create(ui_Container11);
    lv_obj_remove_style_all(ui_envirContain);
    lv_obj_set_width(ui_envirContain, 660);
    lv_obj_set_height(ui_envirContain, 100);
    lv_obj_set_x(ui_envirContain, 26);
    lv_obj_set_y(ui_envirContain, -114);
    lv_obj_set_align(ui_envirContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_envirContain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_envirContain, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_envirContain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_envirContain, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secureContain = lv_obj_create(ui_envirContain);
    lv_obj_remove_style_all(ui_secureContain);
    lv_obj_set_width(ui_secureContain, 165);
    lv_obj_set_height(ui_secureContain, 100);
    lv_obj_set_x(ui_secureContain, -247);
    lv_obj_set_y(ui_secureContain, 0);
    lv_obj_set_align(ui_secureContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_secureContain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_secureContain, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_secureContain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_secureContain, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container19 = lv_obj_create(ui_secureContain);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, 50);
    lv_obj_set_height(ui_Container19, 50);
    lv_obj_set_x(ui_Container19, -47);
    lv_obj_set_y(ui_Container19, 4);
    lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container19, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container19, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_secureContain);
    lv_obj_set_width(ui_TextArea1, 86);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_TextArea1, 28);
    lv_obj_set_y(ui_TextArea1, 0);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "Safety");
    lv_textarea_set_one_line(ui_TextArea1, true);
    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label1 = lv_label_create(ui_secureContain);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 9);
    lv_obj_set_y(ui_Label1, -36);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SECURITY STATUS");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempContain = lv_obj_create(ui_envirContain);
    lv_obj_remove_style_all(ui_tempContain);
    lv_obj_set_width(ui_tempContain, 165);
    lv_obj_set_height(ui_tempContain, 100);
    lv_obj_set_x(ui_tempContain, 84);
    lv_obj_set_y(ui_tempContain, 1);
    lv_obj_set_align(ui_tempContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tempContain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_tempContain, lv_color_hex(0xD7D7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempContain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tempContain, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_tempContain);
    lv_img_set_src(ui_Image7, &ui_img_temp_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -47);
    lv_obj_set_y(ui_Image7, 4);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_tempContain);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 9);
    lv_obj_set_y(ui_Label5, -36);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "CLIMATE AVG");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempText = lv_textarea_create(ui_tempContain);
    lv_obj_set_width(ui_tempText, 69);
    lv_obj_set_height(ui_tempText, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_tempText, 28);
    lv_obj_set_y(ui_tempText, 0);
    lv_obj_set_align(ui_tempText, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_tempText, "33°C");
    lv_textarea_set_one_line(ui_tempText, true);
    lv_obj_set_style_text_color(ui_tempText, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempText, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tempText, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_humdContain = lv_obj_create(ui_envirContain);
    lv_obj_remove_style_all(ui_humdContain);
    lv_obj_set_width(ui_humdContain, 165);
    lv_obj_set_height(ui_humdContain, 100);
    lv_obj_set_x(ui_humdContain, 249);
    lv_obj_set_y(ui_humdContain, 0);
    lv_obj_set_align(ui_humdContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_humdContain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_humdContain, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_humdContain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_humdContain, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_humdContain);
    lv_img_set_src(ui_Image8, &ui_img_humd_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, -47);
    lv_obj_set_y(ui_Image8, 4);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_humdContain);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 9);
    lv_obj_set_y(ui_Label8, -36);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "SECURITY STATUS");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humdText = lv_textarea_create(ui_humdContain);
    lv_obj_set_width(ui_humdText, 67);
    lv_obj_set_height(ui_humdText, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_humdText, 28);
    lv_obj_set_y(ui_humdText, 0);
    lv_obj_set_align(ui_humdText, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_humdText, "42%");
    lv_textarea_set_one_line(ui_humdText, true);
    lv_obj_set_style_text_color(ui_humdText, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humdText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humdText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_humdText, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_humdText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_humdText, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_humdText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_electContain = lv_obj_create(ui_envirContain);
    lv_obj_remove_style_all(ui_electContain);
    lv_obj_set_width(ui_electContain, 165);
    lv_obj_set_height(ui_electContain, 100);
    lv_obj_set_x(ui_electContain, -82);
    lv_obj_set_y(ui_electContain, -1);
    lv_obj_set_align(ui_electContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_electContain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_electContain, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_electContain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_electContain, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_electContain);
    lv_img_set_src(ui_Image2, &ui_img_light1_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -47);
    lv_obj_set_y(ui_Image2, 4);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_electContain);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 9);
    lv_obj_set_y(ui_Label4, -36);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SECURITY STATUS");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_electText = lv_textarea_create(ui_electContain);
    lv_obj_set_width(ui_electText, 96);
    lv_obj_set_height(ui_electText, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_electText, 28);
    lv_obj_set_y(ui_electText, 0);
    lv_obj_set_align(ui_electText, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_electText, "1.24KW");
    lv_textarea_set_one_line(ui_electText, true);
    lv_obj_set_style_text_color(ui_electText, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_electText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_electText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_electText, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_electText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_electText, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_electText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel5 = lv_obj_create(ui_Container11);
    lv_obj_set_width(ui_Panel5, 660);
    lv_obj_set_height(ui_Panel5, 259);
    lv_obj_set_x(ui_Panel5, 24);
    lv_obj_set_y(ui_Panel5, 79);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_dir(ui_Panel5, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemContain = lv_obj_create(ui_Panel5);
    lv_obj_remove_style_all(ui_systemContain);
    lv_obj_set_width(ui_systemContain, 640);
    lv_obj_set_height(ui_systemContain, 229);
    lv_obj_set_x(ui_systemContain, -342);
    lv_obj_set_y(ui_systemContain, -37);
    lv_obj_set_align(ui_systemContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_systemContain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_systemContain);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -8);
    lv_obj_set_y(ui_Label2, -98);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SYSTEM INFRASTRUCTURE");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_systemContain);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 205);
    lv_obj_set_height(ui_Container12, 192);
    lv_obj_set_x(ui_Container12, -215);
    lv_obj_set_y(ui_Container12, 15);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container12, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container12, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_therImgButt = lv_imgbtn_create(ui_Container12);
    lv_imgbtn_set_src(ui_therImgButt, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_closenest_png, NULL);
    lv_imgbtn_set_src(ui_therImgButt, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_opennest_png, NULL);
    lv_imgbtn_set_src(ui_therImgButt, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_therImgButt, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_closelig_png, NULL);
    lv_imgbtn_set_src(ui_therImgButt, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_openice_png, NULL);
    lv_imgbtn_set_src(ui_therImgButt, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_therImgButt, 52);
    lv_obj_set_width(ui_therImgButt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_therImgButt, -68);
    lv_obj_set_y(ui_therImgButt, -54);
    lv_obj_set_align(ui_therImgButt, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -35);
    lv_obj_set_y(ui_Label3, 20);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Main Hall");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -1);
    lv_obj_set_y(ui_Label6, -8);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Thermometer");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Container12);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 15);
    lv_obj_set_height(ui_Container5, 15);
    lv_obj_set_x(ui_Container5, 74);
    lv_obj_set_y(ui_Container5, -71);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_intempText = lv_textarea_create(ui_Container12);
    lv_obj_set_width(ui_intempText, 84);
    lv_obj_set_height(ui_intempText, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_intempText, -38);
    lv_obj_set_y(ui_intempText, 55);
    lv_obj_set_align(ui_intempText, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_intempText, "33°C");
    lv_textarea_set_one_line(ui_intempText, true);
    lv_obj_set_style_text_color(ui_intempText, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_intempText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_intempText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_intempText, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_intempText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_intempText, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_intempText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Container13 = lv_obj_create(ui_systemContain);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 205);
    lv_obj_set_height(ui_Container13, 192);
    lv_obj_set_x(ui_Container13, 0);
    lv_obj_set_y(ui_Container13, 15);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container13, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container13, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container13, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iceButt = lv_imgbtn_create(ui_Container13);
    lv_imgbtn_set_src(ui_iceButt, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_closeice_png, NULL);
    lv_imgbtn_set_src(ui_iceButt, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_openice_png, NULL);
    lv_imgbtn_set_src(ui_iceButt, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_iceButt, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_closelig_png, NULL);
    lv_imgbtn_set_src(ui_iceButt, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_iceButt, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_iceButt, 52);
    lv_obj_set_width(ui_iceButt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_iceButt, -68);
    lv_obj_set_y(ui_iceButt, -54);
    lv_obj_set_align(ui_iceButt, LV_ALIGN_CENTER);

    ui_Label12 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -26);
    lv_obj_set_y(ui_Label12, 18);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Bed Room");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -43);
    lv_obj_set_y(ui_Label9, -8);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "AC Unit");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Container13);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 15);
    lv_obj_set_height(ui_Container3, 15);
    lv_obj_set_x(ui_Container3, 74);
    lv_obj_set_y(ui_Container3, -71);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iceArc = lv_arc_create(ui_Container13);
    lv_obj_set_width(ui_iceArc, 67);
    lv_obj_set_height(ui_iceArc, 62);
    lv_obj_set_x(ui_iceArc, 55);
    lv_obj_set_y(ui_iceArc, 55);
    lv_obj_set_align(ui_iceArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_iceArc, 16, 35);
    lv_arc_set_value(ui_iceArc, 25);


    ui_iceLabel = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_iceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iceLabel, -43);
    lv_obj_set_y(ui_iceLabel, 55);
    lv_obj_set_align(ui_iceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iceLabel, "25°C");
    lv_obj_set_style_text_color(ui_iceLabel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iceLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iceLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_systemContain);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 205);
    lv_obj_set_height(ui_Container14, 192);
    lv_obj_set_x(ui_Container14, 216);
    lv_obj_set_y(ui_Container14, 15);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container14, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container14, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airButt = lv_imgbtn_create(ui_Container14);
    lv_imgbtn_set_src(ui_airButt, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_closeclean_png, NULL);
    lv_imgbtn_set_src(ui_airButt, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_openclean_png, NULL);
    lv_imgbtn_set_src(ui_airButt, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_airButt, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_closelig_png, NULL);
    lv_imgbtn_set_src(ui_airButt, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_airButt, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_airButt, 52);
    lv_obj_set_width(ui_airButt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_airButt, -68);
    lv_obj_set_y(ui_airButt, -54);
    lv_obj_set_align(ui_airButt, LV_ALIGN_CENTER);

    ui_Label13 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -35);
    lv_obj_set_y(ui_Label13, 19);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Bed Room");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -25);
    lv_obj_set_y(ui_Label14, -8);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Air Purifier");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_Container14);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 15);
    lv_obj_set_height(ui_Container15, 15);
    lv_obj_set_x(ui_Container15, 74);
    lv_obj_set_y(ui_Container15, -71);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container15, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airText = lv_textarea_create(ui_Container14);
    lv_obj_set_width(ui_airText, 97);
    lv_obj_set_height(ui_airText, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_airText, -38);
    lv_obj_set_y(ui_airText, 55);
    lv_obj_set_align(ui_airText, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_airText, "AQI:12");
    lv_textarea_set_one_line(ui_airText, true);
    lv_obj_set_style_text_color(ui_airText, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_airText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_airText, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_airText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_airText, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_airText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_lightContain = lv_obj_create(ui_Panel5);
    lv_obj_remove_style_all(ui_lightContain);
    lv_obj_set_width(ui_lightContain, 640);
    lv_obj_set_height(ui_lightContain, 229);
    lv_obj_set_x(ui_lightContain, 1239);
    lv_obj_set_y(ui_lightContain, -16);
    lv_obj_set_align(ui_lightContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lightContain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_lightContain);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -8);
    lv_obj_set_y(ui_Label25, -98);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "LIGHTING CONTROL");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container24 = lv_obj_create(ui_lightContain);
    lv_obj_remove_style_all(ui_Container24);
    lv_obj_set_width(ui_Container24, 205);
    lv_obj_set_height(ui_Container24, 192);
    lv_obj_set_x(ui_Container24, -215);
    lv_obj_set_y(ui_Container24, 15);
    lv_obj_set_align(ui_Container24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container24, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container24, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container24, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton7 = lv_imgbtn_create(ui_Container24);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_closelig_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_openlig_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_closelig_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButton7, 52);
    lv_obj_set_width(ui_ImgButton7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton7, -68);
    lv_obj_set_y(ui_ImgButton7, -54);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);

    ui_Label11 = lv_label_create(ui_Container24);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -8);
    lv_obj_set_y(ui_Label11, 18);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Master bedroom");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Container24);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -31);
    lv_obj_set_y(ui_Label16, -8);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Main light");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider7 = lv_slider_create(ui_Container24);
    lv_slider_set_value(ui_Slider7, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider7) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider7, 172);
    lv_obj_set_height(ui_Slider7, 10);
    lv_obj_set_x(ui_Slider7, 5);
    lv_obj_set_y(ui_Slider7, 68);
    lv_obj_set_align(ui_Slider7, LV_ALIGN_CENTER);


    ui_Label17 = lv_label_create(ui_Container24);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -19);
    lv_obj_set_y(ui_Label17, 41);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Intensity");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sliderLabel7 = lv_label_create(ui_Container24);
    lv_obj_set_width(ui_sliderLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sliderLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sliderLabel7, 76);
    lv_obj_set_y(ui_sliderLabel7, 46);
    lv_obj_set_align(ui_sliderLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sliderLabel7, "20%");
    lv_obj_set_style_text_color(ui_sliderLabel7, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sliderLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Container24);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 15);
    lv_obj_set_height(ui_Container6, 15);
    lv_obj_set_x(ui_Container6, 74);
    lv_obj_set_y(ui_Container6, -71);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container6, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_lightContain);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 205);
    lv_obj_set_height(ui_Container16, 192);
    lv_obj_set_x(ui_Container16, 0);
    lv_obj_set_y(ui_Container16, 15);
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container16, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container16, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_Container16);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_closelig_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_openlig_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_closelig_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButton2, 52);
    lv_obj_set_width(ui_ImgButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton2, -68);
    lv_obj_set_y(ui_ImgButton2, -54);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_Label18 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -26);
    lv_obj_set_y(ui_Label18, 18);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Living room");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -7);
    lv_obj_set_y(ui_Label19, -8);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Auxiliary light");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Container16);
    lv_slider_set_value(ui_Slider2, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 172);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, 5);
    lv_obj_set_y(ui_Slider2, 68);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);


    ui_Label20 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -19);
    lv_obj_set_y(ui_Label20, 41);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Intensity");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sliderLabel2 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_sliderLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sliderLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sliderLabel2, 76);
    lv_obj_set_y(ui_sliderLabel2, 46);
    lv_obj_set_align(ui_sliderLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sliderLabel2, "20%");
    lv_obj_set_style_text_color(ui_sliderLabel2, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sliderLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container20 = lv_obj_create(ui_Container16);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, 15);
    lv_obj_set_height(ui_Container20, 15);
    lv_obj_set_x(ui_Container20, 74);
    lv_obj_set_y(ui_Container20, -71);
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container20, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container20, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container21 = lv_obj_create(ui_lightContain);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_width(ui_Container21, 205);
    lv_obj_set_height(ui_Container21, 192);
    lv_obj_set_x(ui_Container21, 216);
    lv_obj_set_y(ui_Container21, 15);
    lv_obj_set_align(ui_Container21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container21, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container21, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container21, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton5 = lv_imgbtn_create(ui_Container21);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_closelig_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_openlig_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_closelig_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButton5, 52);
    lv_obj_set_width(ui_ImgButton5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton5, -68);
    lv_obj_set_y(ui_ImgButton5, -54);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);

    ui_Label21 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -46);
    lv_obj_set_y(ui_Label21, 18);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "KITCHEN");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -25);
    lv_obj_set_y(ui_Label22, -8);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Other light");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider5 = lv_slider_create(ui_Container21);
    lv_slider_set_value(ui_Slider5, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider5, 172);
    lv_obj_set_height(ui_Slider5, 10);
    lv_obj_set_x(ui_Slider5, 5);
    lv_obj_set_y(ui_Slider5, 68);
    lv_obj_set_align(ui_Slider5, LV_ALIGN_CENTER);


    ui_Label23 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -19);
    lv_obj_set_y(ui_Label23, 41);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Intensity");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sliderLabel5 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_sliderLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sliderLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sliderLabel5, 76);
    lv_obj_set_y(ui_sliderLabel5, 46);
    lv_obj_set_align(ui_sliderLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sliderLabel5, "20%");
    lv_obj_set_style_text_color(ui_sliderLabel5, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sliderLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container22 = lv_obj_create(ui_Container21);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_width(ui_Container22, 15);
    lv_obj_set_height(ui_Container22, 15);
    lv_obj_set_x(ui_Container22, 74);
    lv_obj_set_y(ui_Container22, -71);
    lv_obj_set_align(ui_Container22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container22, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container22, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lifeContain = lv_obj_create(ui_Panel5);
    lv_obj_remove_style_all(ui_lifeContain);
    lv_obj_set_width(ui_lifeContain, 640);
    lv_obj_set_height(ui_lifeContain, 229);
    lv_obj_set_x(ui_lifeContain, -348);
    lv_obj_set_y(ui_lifeContain, -5);
    lv_obj_set_align(ui_lifeContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lifeContain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_lifeContain);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -8);
    lv_obj_set_y(ui_Label29, -98);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "SYSTEM INFRASTRUCTURE");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container30 = lv_obj_create(ui_lifeContain);
    lv_obj_remove_style_all(ui_Container30);
    lv_obj_set_width(ui_Container30, 205);
    lv_obj_set_height(ui_Container30, 192);
    lv_obj_set_x(ui_Container30, -215);
    lv_obj_set_y(ui_Container30, 15);
    lv_obj_set_align(ui_Container30, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container30, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container30, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container30, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container30, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton10 = lv_imgbtn_create(ui_Container30);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_closereg_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_openreg_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_closelig_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButton10, 52);
    lv_obj_set_width(ui_ImgButton10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton10, -68);
    lv_obj_set_y(ui_ImgButton10, -54);
    lv_obj_set_align(ui_ImgButton10, LV_ALIGN_CENTER);

    ui_Label7 = lv_label_create(ui_Container30);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -19);
    lv_obj_set_y(ui_Label7, 20);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Living room");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Container30);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -7);
    lv_obj_set_y(ui_Label10, -7);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Refrigerator");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container23 = lv_obj_create(ui_Container30);
    lv_obj_remove_style_all(ui_Container23);
    lv_obj_set_width(ui_Container23, 15);
    lv_obj_set_height(ui_Container23, 15);
    lv_obj_set_x(ui_Container23, 74);
    lv_obj_set_y(ui_Container23, -71);
    lv_obj_set_align(ui_Container23, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container23, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container23, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea12 = lv_textarea_create(ui_Container30);
    lv_obj_set_width(ui_TextArea12, 139);
    lv_obj_set_height(ui_TextArea12, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_TextArea12, -1);
    lv_obj_set_y(ui_TextArea12, 57);
    lv_obj_set_align(ui_TextArea12, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea12, "Freeze:33°C");
    lv_textarea_set_one_line(ui_TextArea12, true);
    lv_obj_set_style_text_color(ui_TextArea12, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea12, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea12, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Container25 = lv_obj_create(ui_lifeContain);
    lv_obj_remove_style_all(ui_Container25);
    lv_obj_set_width(ui_Container25, 205);
    lv_obj_set_height(ui_Container25, 192);
    lv_obj_set_x(ui_Container25, 0);
    lv_obj_set_y(ui_Container25, 15);
    lv_obj_set_align(ui_Container25, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container25, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container25, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container25, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton6 = lv_imgbtn_create(ui_Container25);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_closewash_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_openwash_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_closelig_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButton6, 52);
    lv_obj_set_width(ui_ImgButton6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton6, -68);
    lv_obj_set_y(ui_ImgButton6, -54);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    ui_Label15 = lv_label_create(ui_Container25);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -35);
    lv_obj_set_y(ui_Label15, 19);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Balcony");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Container25);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -2);
    lv_obj_set_y(ui_Label24, -6);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Wash machine");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container26 = lv_obj_create(ui_Container25);
    lv_obj_remove_style_all(ui_Container26);
    lv_obj_set_width(ui_Container26, 15);
    lv_obj_set_height(ui_Container26, 15);
    lv_obj_set_x(ui_Container26, 74);
    lv_obj_set_y(ui_Container26, -71);
    lv_obj_set_align(ui_Container26, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container26, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container26, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container26, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container27 = lv_obj_create(ui_lifeContain);
    lv_obj_remove_style_all(ui_Container27);
    lv_obj_set_width(ui_Container27, 205);
    lv_obj_set_height(ui_Container27, 192);
    lv_obj_set_x(ui_Container27, 216);
    lv_obj_set_y(ui_Container27, 15);
    lv_obj_set_align(ui_Container27, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container27, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container27, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container27, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container27, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton8 = lv_imgbtn_create(ui_Container27);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_closecur_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_opencur_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_closelig_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButton8, 52);
    lv_obj_set_width(ui_ImgButton8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton8, -68);
    lv_obj_set_y(ui_ImgButton8, -54);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_CENTER);

    ui_Label26 = lv_label_create(ui_Container27);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -35);
    lv_obj_set_y(ui_Label26, 19);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Bed Room");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Container27);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -25);
    lv_obj_set_y(ui_Label27, -8);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Air Purifier");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container28 = lv_obj_create(ui_Container27);
    lv_obj_remove_style_all(ui_Container28);
    lv_obj_set_width(ui_Container28, 15);
    lv_obj_set_height(ui_Container28, 15);
    lv_obj_set_x(ui_Container28, 74);
    lv_obj_set_y(ui_Container28, -71);
    lv_obj_set_align(ui_Container28, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container28, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container28, lv_color_hex(0x439BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_mainFunBut1, ui_event_mainFunBut1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_houseFunBut1, ui_event_houseFunBut1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tipsFunBut1, ui_event_tipsFunBut1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_musicrFunBut1, ui_event_musicrFunBut1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sumspeakButt2, ui_event_sumspeakButt2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_closeImgButton2, ui_event_closeImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_therImgButt, ui_event_therImgButt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_iceButt, ui_event_iceButt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_iceArc, ui_event_iceArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_airButt, ui_event_airButt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton7, ui_event_ImgButton7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider7, ui_event_Slider7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider5, ui_event_Slider5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton10, ui_event_ImgButton10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton8, ui_event_ImgButton8, LV_EVENT_ALL, NULL);

}
