// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_loginScreen_screen_init(void)
{
    ui_loginScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_loginScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loginWin = lv_obj_create(ui_loginScreen);
    lv_obj_remove_style_all(ui_loginWin);
    lv_obj_set_width(ui_loginWin, 800);
    lv_obj_set_height(ui_loginWin, 480);
    lv_obj_set_align(ui_loginWin, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_loginWin, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_loginWin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_loginWin, lv_color_hex(0x29B7CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loginWin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_loginWin, &ui_img_ironman_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_loginWin);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 520);
    lv_obj_set_height(ui_Container2, 220);
    lv_obj_set_x(ui_Container2, 4);
    lv_obj_set_y(ui_Container2, 126);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0x1589BB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea5 = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_TextArea5, 420);
    lv_obj_set_height(ui_TextArea5, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea5, 0);
    lv_obj_set_y(ui_TextArea5, -40);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea5, "> SYSTEM ONLINE. AWAITING COMMAND.");
    lv_textarea_set_placeholder_text(ui_TextArea5, "Placeholder...");
    lv_textarea_set_one_line(ui_TextArea5, true);
    lv_obj_set_style_text_color(ui_TextArea5, lv_color_hex(0x12759F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Container4 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 430);
    lv_obj_set_height(ui_Container4, 140);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container4, lv_color_hex(0x12749F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loginButton = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_loginButton, 253);
    lv_obj_set_height(ui_loginButton, 50);
    lv_obj_set_x(ui_loginButton, -14);
    lv_obj_set_y(ui_loginButton, 44);
    lv_obj_set_align(ui_loginButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loginButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_loginButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_loginButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_loginButton, lv_color_hex(0x000507), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loginButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_loginButton, lv_color_hex(0x12759F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_loginButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_loginButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loginlable = lv_label_create(ui_loginButton);
    lv_obj_set_width(ui_loginlable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loginlable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_loginlable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loginlable, "Start up");
    lv_obj_set_style_text_color(ui_loginlable, lv_color_hex(0x12749F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_loginlable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 45);
    lv_obj_set_height(ui_Container7, 40);
    lv_obj_set_x(ui_Container7, -237);
    lv_obj_set_y(ui_Container7, -89);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container7, lv_color_hex(0x12749F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 45);
    lv_obj_set_height(ui_Container8, 40);
    lv_obj_set_x(ui_Container8, 236);
    lv_obj_set_y(ui_Container8, 89);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container8, lv_color_hex(0x12749F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 45);
    lv_obj_set_height(ui_Container9, 40);
    lv_obj_set_x(ui_Container9, 236);
    lv_obj_set_y(ui_Container9, -89);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container9, lv_color_hex(0x12749F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 45);
    lv_obj_set_height(ui_Container10, 40);
    lv_obj_set_x(ui_Container10, -237);
    lv_obj_set_y(ui_Container10, 89);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container10, lv_color_hex(0x12759F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_loginButton, ui_event_loginButton, LV_EVENT_ALL, NULL);

}
