// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_musicScreen_screen_init(void)
{
    ui_musicScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_musicScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_musicScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_musicScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_musicScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_musicScreen, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container17 = lv_obj_create(ui_musicScreen);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, 800);
    lv_obj_set_height(ui_Container17, 480);
    lv_obj_set_align(ui_Container17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container17, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftsideContain3 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_leftsideContain3);
    lv_obj_set_width(ui_leftsideContain3, 60);
    lv_obj_set_height(ui_leftsideContain3, 430);
    lv_obj_set_x(ui_leftsideContain3, -370);
    lv_obj_set_y(ui_leftsideContain3, 25);
    lv_obj_set_align(ui_leftsideContain3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leftsideContain3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leftsideContain3, lv_color_hex(0x080404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftsideContain3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_leftsideContain3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_leftsideContain3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_leftsideContain3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainFunBut2 = lv_imgbtn_create(ui_leftsideContain3);
    lv_imgbtn_set_src(ui_mainFunBut2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_mainfunct_png, NULL);
    lv_imgbtn_set_src(ui_mainFunBut2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_mainfunct_png, NULL);
    lv_imgbtn_set_src(ui_mainFunBut2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_mainFunBut2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_mainFunBut2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_mainFunBut2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_mainFunBut2, 35);
    lv_obj_set_width(ui_mainFunBut2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_mainFunBut2, 0);
    lv_obj_set_y(ui_mainFunBut2, -170);
    lv_obj_set_align(ui_mainFunBut2, LV_ALIGN_CENTER);

    ui_houseFunBut2 = lv_imgbtn_create(ui_leftsideContain3);
    lv_imgbtn_set_src(ui_houseFunBut2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
    lv_imgbtn_set_src(ui_houseFunBut2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_png, NULL);
    lv_imgbtn_set_src(ui_houseFunBut2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_houseFunBut2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_houseFunBut2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_houseFunBut2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_houseFunBut2, 35);
    lv_obj_set_width(ui_houseFunBut2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_houseFunBut2, 0);
    lv_obj_set_y(ui_houseFunBut2, -110);
    lv_obj_set_align(ui_houseFunBut2, LV_ALIGN_CENTER);

    ui_tipsFunBut2 = lv_imgbtn_create(ui_leftsideContain3);
    lv_imgbtn_set_src(ui_tipsFunBut2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_video_png, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_video_png, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_tipsFunBut2, 35);
    lv_obj_set_width(ui_tipsFunBut2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_tipsFunBut2, 0);
    lv_obj_set_y(ui_tipsFunBut2, 10);
    lv_obj_set_align(ui_tipsFunBut2, LV_ALIGN_CENTER);

    ui_musicrFunBut2 = lv_imgbtn_create(ui_leftsideContain3);
    lv_imgbtn_set_src(ui_musicrFunBut2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_music2_png, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_music2_png, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_musicrFunBut2, 35);
    lv_obj_set_width(ui_musicrFunBut2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_musicrFunBut2, 0);
    lv_obj_set_y(ui_musicrFunBut2, -50);
    lv_obj_set_align(ui_musicrFunBut2, LV_ALIGN_CENTER);

    ui_Panel12 = lv_obj_create(ui_leftsideContain3);
    lv_obj_set_width(ui_Panel12, 50);
    lv_obj_set_height(ui_Panel12, 50);
    lv_obj_set_x(ui_Panel12, 0);
    lv_obj_set_y(ui_Panel12, 174);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x080404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x17A5E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sumspeakButt3 = lv_imgbtn_create(ui_Panel12);
    lv_imgbtn_set_src(ui_sumspeakButt3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_speak_png, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_speak_png, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_sumspeakButt3, 31);
    lv_obj_set_width(ui_sumspeakButt3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_sumspeakButt3, -1);
    lv_obj_set_y(ui_sumspeakButt3, 0);
    lv_obj_set_align(ui_sumspeakButt3, LV_ALIGN_CENTER);

    ui_upsideContain3 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_upsideContain3);
    lv_obj_set_width(ui_upsideContain3, 740);
    lv_obj_set_height(ui_upsideContain3, 50);
    lv_obj_set_x(ui_upsideContain3, 29);
    lv_obj_set_y(ui_upsideContain3, -213);
    lv_obj_set_align(ui_upsideContain3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_upsideContain3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_upsideContain3, lv_color_hex(0x030000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_upsideContain3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_upsideContain3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_upsideContain3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_upsideContain3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_signImage3 = lv_img_create(ui_upsideContain3);
    lv_img_set_src(ui_signImage3, &ui_img_jarvis3_png);
    lv_obj_set_width(ui_signImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_signImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_signImage3, -38);
    lv_obj_set_y(ui_signImage3, 1);
    lv_obj_set_align(ui_signImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_signImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_signImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rightContain2 = lv_obj_create(ui_upsideContain3);
    lv_obj_remove_style_all(ui_rightContain2);
    lv_obj_set_width(ui_rightContain2, 100);
    lv_obj_set_height(ui_rightContain2, 44);
    lv_obj_set_x(ui_rightContain2, 252);
    lv_obj_set_y(ui_rightContain2, 1);
    lv_obj_set_align(ui_rightContain2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rightContain2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time3 = lv_label_create(ui_rightContain2);
    lv_obj_set_width(ui_time3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time3, 24);
    lv_obj_set_y(ui_time3, 1);
    lv_obj_set_align(ui_time3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time3, "15:30:56");
    lv_obj_set_style_text_color(ui_time3, lv_color_hex(0xE1E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeImage3 = lv_img_create(ui_rightContain2);
    lv_img_set_src(ui_timeImage3, &ui_img_time_png);
    lv_obj_set_width(ui_timeImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeImage3, -22);
    lv_obj_set_y(ui_timeImage3, 0);
    lv_obj_set_align(ui_timeImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_timeImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiImage3 = lv_img_create(ui_upsideContain3);
    lv_img_set_src(ui_wifiImage3, &ui_img_wifi__png);
    lv_obj_set_width(ui_wifiImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiImage3, 333);
    lv_obj_set_y(ui_wifiImage3, 0);
    lv_obj_set_align(ui_wifiImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sideContain2 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_sideContain2);
    lv_obj_set_width(ui_sideContain2, 60);
    lv_obj_set_height(ui_sideContain2, 50);
    lv_obj_set_x(ui_sideContain2, -370);
    lv_obj_set_y(ui_sideContain2, -213);
    lv_obj_set_align(ui_sideContain2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sideContain2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sideContain2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sideContain2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sideContain2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sideContain2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sideContain2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_closeImgButton3 = lv_imgbtn_create(ui_sideContain2);
    lv_imgbtn_set_src(ui_closeImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_shutdown_png, NULL);
    lv_imgbtn_set_src(ui_closeImgButton3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_shutdown_png, NULL);
    lv_imgbtn_set_src(ui_closeImgButton3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_closeImgButton3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_closeImgButton3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_closeImgButton3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_closeImgButton3, 34);
    lv_obj_set_width(ui_closeImgButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_closeImgButton3, LV_ALIGN_CENTER);

    ui_Container29 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Container29);
    lv_obj_set_width(ui_Container29, 735);
    lv_obj_set_height(ui_Container29, 423);
    lv_obj_set_x(ui_Container29, 29);
    lv_obj_set_y(ui_Container29, 24);
    lv_obj_set_align(ui_Container29, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container29, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container31 = lv_obj_create(ui_Container29);
    lv_obj_remove_style_all(ui_Container31);
    lv_obj_set_width(ui_Container31, 735);
    lv_obj_set_height(ui_Container31, 85);
    lv_obj_set_x(ui_Container31, 0);
    lv_obj_set_y(ui_Container31, 170);
    lv_obj_set_align(ui_Container31, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container31, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_stopButt = lv_imgbtn_create(ui_Container31);
    lv_imgbtn_set_src(ui_stopButt, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_stop_png, NULL);
    lv_imgbtn_set_src(ui_stopButt, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_start_png, NULL);
    lv_imgbtn_set_src(ui_stopButt, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_stopButt, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_stopButt, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_stopButt, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_stopButt, 50);
    lv_obj_set_width(ui_stopButt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_stopButt, -15);
    lv_obj_set_y(ui_stopButt, 0);
    lv_obj_set_align(ui_stopButt, LV_ALIGN_CENTER);

    ui_nextButt = lv_imgbtn_create(ui_Container31);
    lv_imgbtn_set_src(ui_nextButt, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_next1_png, NULL);
    lv_imgbtn_set_src(ui_nextButt, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_next2_png, NULL);
    lv_imgbtn_set_src(ui_nextButt, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextButt, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextButt, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextButt, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_nextButt, 50);
    lv_obj_set_width(ui_nextButt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_nextButt, 70);
    lv_obj_set_y(ui_nextButt, 0);
    lv_obj_set_align(ui_nextButt, LV_ALIGN_CENTER);

    ui_lastButt = lv_imgbtn_create(ui_Container31);
    lv_imgbtn_set_src(ui_lastButt, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_last2_png, NULL);
    lv_imgbtn_set_src(ui_lastButt, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1363945504, NULL);
    lv_imgbtn_set_src(ui_lastButt, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastButt, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastButt, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastButt, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_lastButt, 50);
    lv_obj_set_width(ui_lastButt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_lastButt, -100);
    lv_obj_set_y(ui_lastButt, 0);
    lv_obj_set_align(ui_lastButt, LV_ALIGN_CENTER);

    ui_songerText = lv_textarea_create(ui_Container31);
    lv_obj_set_width(ui_songerText, 191);
    lv_obj_set_height(ui_songerText, 70);
    lv_obj_set_x(ui_songerText, -259);
    lv_obj_set_y(ui_songerText, 0);
    lv_obj_set_align(ui_songerText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_songerText, "Song Information");
    lv_obj_set_style_text_color(ui_songerText, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_songerText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_songerText, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_songerText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Slider1 = lv_slider_create(ui_Container31);
    lv_slider_set_value(ui_Slider1, 80, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 12);
    lv_obj_set_x(ui_Slider1, 250);
    lv_obj_set_y(ui_Slider1, 0);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    ui_Image1 = lv_img_create(ui_Container31);
    lv_img_set_src(ui_Image1, &ui_img_soun2_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 150);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_soundLabel = lv_label_create(ui_Container31);
    lv_obj_set_width(ui_soundLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soundLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soundLabel, 345);
    lv_obj_set_y(ui_soundLabel, -1);
    lv_obj_set_align(ui_soundLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_soundLabel, "80%");
    lv_obj_set_style_text_color(ui_soundLabel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_soundLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Container17);
    lv_obj_set_width(ui_Panel8, 738);
    lv_obj_set_height(ui_Panel8, 50);
    lv_obj_set_x(ui_Panel8, 62);
    lv_obj_set_y(ui_Panel8, -83);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Panel8, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeSlider2 = lv_slider_create(ui_Panel8);
    lv_slider_set_value(ui_timeSlider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_timeSlider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_timeSlider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_timeSlider2, 620);
    lv_obj_set_height(ui_timeSlider2, 10);
    lv_obj_set_x(ui_timeSlider2, -10);
    lv_obj_set_y(ui_timeSlider2, 0);
    lv_obj_set_align(ui_timeSlider2, LV_ALIGN_BOTTOM_LEFT);


    ui_timeContainer2 = lv_obj_create(ui_Panel8);
    lv_obj_remove_style_all(ui_timeContainer2);
    lv_obj_set_width(ui_timeContainer2, 100);
    lv_obj_set_height(ui_timeContainer2, 45);
    lv_obj_set_x(ui_timeContainer2, 314);
    lv_obj_set_y(ui_timeContainer2, -3);
    lv_obj_set_align(ui_timeContainer2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timeContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sumtimeLabel2 = lv_label_create(ui_timeContainer2);
    lv_obj_set_width(ui_sumtimeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sumtimeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sumtimeLabel2, 25);
    lv_obj_set_y(ui_sumtimeLabel2, 0);
    lv_obj_set_align(ui_sumtimeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sumtimeLabel2, "time");
    lv_obj_set_style_text_color(ui_sumtimeLabel2, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sumtimeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowtimeLabel2 = lv_label_create(ui_timeContainer2);
    lv_obj_set_width(ui_nowtimeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nowtimeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nowtimeLabel2, -25);
    lv_obj_set_y(ui_nowtimeLabel2, 0);
    lv_obj_set_align(ui_nowtimeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nowtimeLabel2, "time");
    lv_obj_set_style_text_color(ui_nowtimeLabel2, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nowtimeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_timeContainer2);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "/");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_videoContain2 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_videoContain2);
    lv_obj_set_width(ui_videoContain2, 738);
    lv_obj_set_height(ui_videoContain2, 343);
    lv_obj_set_x(ui_videoContain2, 29);
    lv_obj_set_y(ui_videoContain2, -17);
    lv_obj_set_align(ui_videoContain2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_videoContain2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel9 = lv_obj_create(ui_videoContain2);
    lv_obj_set_width(ui_Panel9, 738);
    lv_obj_set_height(ui_Panel9, 50);
    lv_obj_set_x(ui_Panel9, 2);
    lv_obj_set_y(ui_Panel9, 2);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeSlider3 = lv_slider_create(ui_Panel9);
    lv_slider_set_value(ui_timeSlider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_timeSlider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_timeSlider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_timeSlider3, 620);
    lv_obj_set_height(ui_timeSlider3, 10);
    lv_obj_set_x(ui_timeSlider3, -10);
    lv_obj_set_y(ui_timeSlider3, 0);
    lv_obj_set_align(ui_timeSlider3, LV_ALIGN_BOTTOM_LEFT);


    ui_timeContainer3 = lv_obj_create(ui_Panel9);
    lv_obj_remove_style_all(ui_timeContainer3);
    lv_obj_set_width(ui_timeContainer3, 100);
    lv_obj_set_height(ui_timeContainer3, 45);
    lv_obj_set_x(ui_timeContainer3, 313);
    lv_obj_set_y(ui_timeContainer3, -3);
    lv_obj_set_align(ui_timeContainer3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timeContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sumtimeLabel3 = lv_label_create(ui_timeContainer3);
    lv_obj_set_width(ui_sumtimeLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sumtimeLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sumtimeLabel3, 25);
    lv_obj_set_y(ui_sumtimeLabel3, 0);
    lv_obj_set_align(ui_sumtimeLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sumtimeLabel3, "time");
    lv_obj_set_style_text_color(ui_sumtimeLabel3, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sumtimeLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowtimeLabel3 = lv_label_create(ui_timeContainer3);
    lv_obj_set_width(ui_nowtimeLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nowtimeLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nowtimeLabel3, -25);
    lv_obj_set_y(ui_nowtimeLabel3, 0);
    lv_obj_set_align(ui_nowtimeLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nowtimeLabel3, "time");
    lv_obj_set_style_text_color(ui_nowtimeLabel3, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nowtimeLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_timeContainer3);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "/");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_videoContain2);
    lv_obj_set_width(ui_Panel11, 200);
    lv_obj_set_height(ui_Panel11, 200);
    lv_obj_set_x(ui_Panel11, -217);
    lv_obj_set_y(ui_Panel11, -12);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x0D3A4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Panel11);
    lv_obj_set_width(ui_Panel7, 170);
    lv_obj_set_height(ui_Panel7, 170);
    lv_obj_set_x(ui_Panel7, -1);
    lv_obj_set_y(ui_Panel7, 1);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x1482B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_musiceCordImage = lv_img_create(ui_Panel7);
    lv_img_set_src(ui_musiceCordImage, &ui_img_core_png);
    lv_obj_set_width(ui_musiceCordImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_musiceCordImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_musiceCordImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_musiceCordImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_musiceCordImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Panel11);
    lv_img_set_src(ui_Image3, &ui_img_line_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 150);

    ui_musicTextArea = lv_textarea_create(ui_videoContain2);
    lv_obj_set_width(ui_musicTextArea, 424);
    lv_obj_set_height(ui_musicTextArea, 258);
    lv_obj_set_x(ui_musicTextArea, 146);
    lv_obj_set_y(ui_musicTextArea, -14);
    lv_obj_set_align(ui_musicTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_musicTextArea, "Music lyrics");
    lv_obj_set_style_text_color(ui_musicTextArea, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_musicTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_musicTextArea, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_musicTextArea, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_musicTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_mainFunBut2, ui_event_mainFunBut2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_houseFunBut2, ui_event_houseFunBut2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tipsFunBut2, ui_event_tipsFunBut2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_musicrFunBut2, ui_event_musicrFunBut2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sumspeakButt3, ui_event_sumspeakButt3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_closeImgButton3, ui_event_closeImgButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stopButt, ui_event_stopButt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_nextButt, ui_event_nextButt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lastButt, ui_event_lastButt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeSlider3, ui_event_timeSlider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_videoContain2, ui_event_videoContain2, LV_EVENT_ALL, NULL);

}
