// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_mainScreen, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 800);
    lv_obj_set_height(ui_Container1, 480);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftsideContain1 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_leftsideContain1);
    lv_obj_set_width(ui_leftsideContain1, 60);
    lv_obj_set_height(ui_leftsideContain1, 430);
    lv_obj_set_x(ui_leftsideContain1, -370);
    lv_obj_set_y(ui_leftsideContain1, 25);
    lv_obj_set_align(ui_leftsideContain1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leftsideContain1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leftsideContain1, lv_color_hex(0x080404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftsideContain1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_leftsideContain1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_leftsideContain1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_leftsideContain1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainFunBut = lv_imgbtn_create(ui_leftsideContain1);
    lv_imgbtn_set_src(ui_mainFunBut, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_mainfunct_png, NULL);
    lv_imgbtn_set_src(ui_mainFunBut, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_mainfunct_png, NULL);
    lv_imgbtn_set_src(ui_mainFunBut, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_mainFunBut, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_mainFunBut, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_mainFunBut, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_mainFunBut, 35);
    lv_obj_set_width(ui_mainFunBut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_mainFunBut, 0);
    lv_obj_set_y(ui_mainFunBut, -170);
    lv_obj_set_align(ui_mainFunBut, LV_ALIGN_CENTER);

    ui_houseFunBut = lv_imgbtn_create(ui_leftsideContain1);
    lv_imgbtn_set_src(ui_houseFunBut, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
    lv_imgbtn_set_src(ui_houseFunBut, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_png, NULL);
    lv_imgbtn_set_src(ui_houseFunBut, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_houseFunBut, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_houseFunBut, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_houseFunBut, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_houseFunBut, 35);
    lv_obj_set_width(ui_houseFunBut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_houseFunBut, 0);
    lv_obj_set_y(ui_houseFunBut, -110);
    lv_obj_set_align(ui_houseFunBut, LV_ALIGN_CENTER);

    ui_tipsFunBut = lv_imgbtn_create(ui_leftsideContain1);
    lv_imgbtn_set_src(ui_tipsFunBut, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_video_png, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_video_png, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_tipsFunBut, 35);
    lv_obj_set_width(ui_tipsFunBut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_tipsFunBut, 0);
    lv_obj_set_y(ui_tipsFunBut, 10);
    lv_obj_set_align(ui_tipsFunBut, LV_ALIGN_CENTER);

    ui_musicrFunBut = lv_imgbtn_create(ui_leftsideContain1);
    lv_imgbtn_set_src(ui_musicrFunBut, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_music2_png, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_music2_png, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_musicrFunBut, 35);
    lv_obj_set_width(ui_musicrFunBut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_musicrFunBut, 0);
    lv_obj_set_y(ui_musicrFunBut, -50);
    lv_obj_set_align(ui_musicrFunBut, LV_ALIGN_CENTER);

    ui_Panel1 = lv_obj_create(ui_leftsideContain1);
    lv_obj_set_width(ui_Panel1, 50);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 174);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x080404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x17A5E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sumspeakButt = lv_imgbtn_create(ui_Panel1);
    lv_imgbtn_set_src(ui_sumspeakButt, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_speak_png, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_speak_png, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_sumspeakButt, 31);
    lv_obj_set_width(ui_sumspeakButt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_sumspeakButt, -1);
    lv_obj_set_y(ui_sumspeakButt, 0);
    lv_obj_set_align(ui_sumspeakButt, LV_ALIGN_CENTER);

    ui_upsideContain1 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_upsideContain1);
    lv_obj_set_width(ui_upsideContain1, 740);
    lv_obj_set_height(ui_upsideContain1, 50);
    lv_obj_set_x(ui_upsideContain1, 29);
    lv_obj_set_y(ui_upsideContain1, -213);
    lv_obj_set_align(ui_upsideContain1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_upsideContain1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_upsideContain1, lv_color_hex(0x030000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_upsideContain1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_upsideContain1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_upsideContain1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_upsideContain1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_signImage1 = lv_img_create(ui_upsideContain1);
    lv_img_set_src(ui_signImage1, &ui_img_jarvis3_png);
    lv_obj_set_width(ui_signImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_signImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_signImage1, -38);
    lv_obj_set_y(ui_signImage1, 1);
    lv_obj_set_align(ui_signImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_signImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_signImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rightContain = lv_obj_create(ui_upsideContain1);
    lv_obj_remove_style_all(ui_rightContain);
    lv_obj_set_width(ui_rightContain, 100);
    lv_obj_set_height(ui_rightContain, 44);
    lv_obj_set_x(ui_rightContain, 252);
    lv_obj_set_y(ui_rightContain, 1);
    lv_obj_set_align(ui_rightContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rightContain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time1 = lv_label_create(ui_rightContain);
    lv_obj_set_width(ui_time1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time1, 24);
    lv_obj_set_y(ui_time1, 1);
    lv_obj_set_align(ui_time1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time1, "15:30:56");
    lv_obj_set_style_text_color(ui_time1, lv_color_hex(0xE1E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeImage1 = lv_img_create(ui_rightContain);
    lv_img_set_src(ui_timeImage1, &ui_img_time_png);
    lv_obj_set_width(ui_timeImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeImage1, -22);
    lv_obj_set_y(ui_timeImage1, 0);
    lv_obj_set_align(ui_timeImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_timeImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiImage1 = lv_img_create(ui_upsideContain1);
    lv_img_set_src(ui_wifiImage1, &ui_img_wifi__png);
    lv_obj_set_width(ui_wifiImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiImage1, 333);
    lv_obj_set_y(ui_wifiImage1, 0);
    lv_obj_set_align(ui_wifiImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sideContain = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_sideContain);
    lv_obj_set_width(ui_sideContain, 60);
    lv_obj_set_height(ui_sideContain, 50);
    lv_obj_set_x(ui_sideContain, -370);
    lv_obj_set_y(ui_sideContain, -213);
    lv_obj_set_align(ui_sideContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sideContain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sideContain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sideContain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sideContain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sideContain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sideContain, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_closeImgButton1 = lv_imgbtn_create(ui_sideContain);
    lv_imgbtn_set_src(ui_closeImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_shutdown_png, NULL);
    lv_imgbtn_set_src(ui_closeImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_shutdown_png, NULL);
    lv_imgbtn_set_src(ui_closeImgButton1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_closeImgButton1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_closeImgButton1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_closeImgButton1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_closeImgButton1, 34);
    lv_obj_set_width(ui_closeImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_closeImgButton1, LV_ALIGN_CENTER);

    ui_enterImgButton1 = lv_imgbtn_create(ui_Container1);
    lv_imgbtn_set_src(ui_enterImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_fly_png, NULL);
    lv_imgbtn_set_src(ui_enterImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_fly_png, NULL);
    lv_imgbtn_set_src(ui_enterImgButton1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_enterImgButton1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_enterImgButton1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_enterImgButton1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_enterImgButton1, 30);
    lv_obj_set_width(ui_enterImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_enterImgButton1, 225);
    lv_obj_set_y(ui_enterImgButton1, 55);
    lv_obj_set_align(ui_enterImgButton1, LV_ALIGN_CENTER);

    ui_speakImgButton1 = lv_imgbtn_create(ui_Container1);
    lv_imgbtn_set_src(ui_speakImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_speak_png, NULL);
    lv_imgbtn_set_src(ui_speakImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_speak_png, NULL);
    lv_imgbtn_set_src(ui_speakImgButton1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_speakImgButton1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_speakImgButton1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_speakImgButton1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_speakImgButton1, 30);
    lv_obj_set_width(ui_speakImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_speakImgButton1, -225);
    lv_obj_set_y(ui_speakImgButton1, 55);
    lv_obj_set_align(ui_speakImgButton1, LV_ALIGN_CENTER);

    ui_ansText = lv_textarea_create(ui_Container1);
    lv_obj_set_width(ui_ansText, 400);
    lv_obj_set_height(ui_ansText, 137);
    lv_obj_set_x(ui_ansText, 0);
    lv_obj_set_y(ui_ansText, 160);
    lv_obj_set_align(ui_ansText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ansText, "                                      Answer");
    lv_obj_set_style_text_color(ui_ansText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ansText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ansText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ansText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_ansText, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ansText, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ansText, &lv_font_montserrat_20, LV_PART_SELECTED | LV_STATE_DEFAULT);


    ui_speakText = lv_textarea_create(ui_mainScreen);
    lv_obj_set_width(ui_speakText, 400);
    lv_obj_set_height(ui_speakText, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_speakText, 0);
    lv_obj_set_y(ui_speakText, 56);
    lv_obj_set_align(ui_speakText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_speakText, "Type or speak a command...");
    lv_textarea_set_one_line(ui_speakText, true);
    lv_obj_set_style_text_color(ui_speakText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speakText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_speakText, lv_color_hex(0x090000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speakText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_speakText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_speakText, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);



    ui_coreContain1 = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_coreContain1);
    lv_obj_set_width(ui_coreContain1, 470);
    lv_obj_set_height(ui_coreContain1, 200);
    lv_obj_set_x(ui_coreContain1, -16);
    lv_obj_set_y(ui_coreContain1, -81);
    lv_obj_set_align(ui_coreContain1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_coreContain1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_coreContain1);
    lv_obj_set_width(ui_Panel3, 200);
    lv_obj_set_height(ui_Panel3, 200);
    lv_obj_set_x(ui_Panel3, 7);
    lv_obj_set_y(ui_Panel3, 0);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x0D3A4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel4, 170);
    lv_obj_set_height(ui_Panel4, 170);
    lv_obj_set_x(ui_Panel4, -1);
    lv_obj_set_y(ui_Panel4, 1);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x1482B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Panel4);
    lv_img_set_src(ui_Image5, &ui_img_core_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_mainScreen);
    lv_obj_set_width(ui_Keyboard1, 740);
    lv_obj_set_height(ui_Keyboard1, 150);
    lv_obj_set_x(ui_Keyboard1, 29);
    lv_obj_set_y(ui_Keyboard1, 165);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_mainFunBut, ui_event_mainFunBut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_houseFunBut, ui_event_houseFunBut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tipsFunBut, ui_event_tipsFunBut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_musicrFunBut, ui_event_musicrFunBut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sumspeakButt, ui_event_sumspeakButt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_closeImgButton1, ui_event_closeImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_enterImgButton1, ui_event_enterImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_speakImgButton1, ui_event_speakImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_speakText, ui_event_speakText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);

}
