// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_videoScreen_screen_init(void)
{
    ui_videoScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_videoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_videoScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_videoScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_videoScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_videoScreen, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container18 = lv_obj_create(ui_videoScreen);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_width(ui_Container18, 800);
    lv_obj_set_height(ui_Container18, 480);
    lv_obj_set_align(ui_Container18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container18, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftsideContain4 = lv_obj_create(ui_Container18);
    lv_obj_remove_style_all(ui_leftsideContain4);
    lv_obj_set_width(ui_leftsideContain4, 60);
    lv_obj_set_height(ui_leftsideContain4, 430);
    lv_obj_set_x(ui_leftsideContain4, -370);
    lv_obj_set_y(ui_leftsideContain4, 25);
    lv_obj_set_align(ui_leftsideContain4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leftsideContain4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leftsideContain4, lv_color_hex(0x080404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftsideContain4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_leftsideContain4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_leftsideContain4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_leftsideContain4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainFunBut3 = lv_imgbtn_create(ui_leftsideContain4);
    lv_imgbtn_set_src(ui_mainFunBut3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_mainfunct_png, NULL);
    lv_imgbtn_set_src(ui_mainFunBut3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_mainfunct_png, NULL);
    lv_imgbtn_set_src(ui_mainFunBut3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_mainFunBut3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_mainFunBut3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_mainFunBut3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_mainFunBut3, 35);
    lv_obj_set_width(ui_mainFunBut3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_mainFunBut3, 0);
    lv_obj_set_y(ui_mainFunBut3, -170);
    lv_obj_set_align(ui_mainFunBut3, LV_ALIGN_CENTER);

    ui_houseFunBut3 = lv_imgbtn_create(ui_leftsideContain4);
    lv_imgbtn_set_src(ui_houseFunBut3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
    lv_imgbtn_set_src(ui_houseFunBut3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_png, NULL);
    lv_imgbtn_set_src(ui_houseFunBut3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_houseFunBut3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_houseFunBut3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_houseFunBut3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_houseFunBut3, 35);
    lv_obj_set_width(ui_houseFunBut3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_houseFunBut3, 0);
    lv_obj_set_y(ui_houseFunBut3, -110);
    lv_obj_set_align(ui_houseFunBut3, LV_ALIGN_CENTER);

    ui_tipsFunBut3 = lv_imgbtn_create(ui_leftsideContain4);
    lv_imgbtn_set_src(ui_tipsFunBut3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_video_png, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_video_png, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_tipsFunBut3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_tipsFunBut3, 35);
    lv_obj_set_width(ui_tipsFunBut3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_tipsFunBut3, 0);
    lv_obj_set_y(ui_tipsFunBut3, 10);
    lv_obj_set_align(ui_tipsFunBut3, LV_ALIGN_CENTER);

    ui_musicrFunBut3 = lv_imgbtn_create(ui_leftsideContain4);
    lv_imgbtn_set_src(ui_musicrFunBut3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_music2_png, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_music2_png, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_musicrFunBut3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_musicrFunBut3, 35);
    lv_obj_set_width(ui_musicrFunBut3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_musicrFunBut3, 0);
    lv_obj_set_y(ui_musicrFunBut3, -50);
    lv_obj_set_align(ui_musicrFunBut3, LV_ALIGN_CENTER);

    ui_Panel13 = lv_obj_create(ui_leftsideContain4);
    lv_obj_set_width(ui_Panel13, 50);
    lv_obj_set_height(ui_Panel13, 50);
    lv_obj_set_x(ui_Panel13, 0);
    lv_obj_set_y(ui_Panel13, 174);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x080404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x17A5E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sumspeakButt4 = lv_imgbtn_create(ui_Panel13);
    lv_imgbtn_set_src(ui_sumspeakButt4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_speak_png, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_speak_png, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt4, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt4, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt4, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_sumspeakButt4, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_sumspeakButt4, 31);
    lv_obj_set_width(ui_sumspeakButt4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_sumspeakButt4, -1);
    lv_obj_set_y(ui_sumspeakButt4, 0);
    lv_obj_set_align(ui_sumspeakButt4, LV_ALIGN_CENTER);

    ui_upsideContain4 = lv_obj_create(ui_Container18);
    lv_obj_remove_style_all(ui_upsideContain4);
    lv_obj_set_width(ui_upsideContain4, 740);
    lv_obj_set_height(ui_upsideContain4, 50);
    lv_obj_set_x(ui_upsideContain4, 29);
    lv_obj_set_y(ui_upsideContain4, -213);
    lv_obj_set_align(ui_upsideContain4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_upsideContain4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_upsideContain4, lv_color_hex(0x030000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_upsideContain4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_upsideContain4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_upsideContain4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_upsideContain4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_signImage4 = lv_img_create(ui_upsideContain4);
    lv_img_set_src(ui_signImage4, &ui_img_jarvis3_png);
    lv_obj_set_width(ui_signImage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_signImage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_signImage4, -38);
    lv_obj_set_y(ui_signImage4, 1);
    lv_obj_set_align(ui_signImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_signImage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_signImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rightContain3 = lv_obj_create(ui_upsideContain4);
    lv_obj_remove_style_all(ui_rightContain3);
    lv_obj_set_width(ui_rightContain3, 100);
    lv_obj_set_height(ui_rightContain3, 44);
    lv_obj_set_x(ui_rightContain3, 252);
    lv_obj_set_y(ui_rightContain3, 1);
    lv_obj_set_align(ui_rightContain3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rightContain3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time4 = lv_label_create(ui_rightContain3);
    lv_obj_set_width(ui_time4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time4, 24);
    lv_obj_set_y(ui_time4, 1);
    lv_obj_set_align(ui_time4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time4, "15:30:56");
    lv_obj_set_style_text_color(ui_time4, lv_color_hex(0xE1E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeImage4 = lv_img_create(ui_rightContain3);
    lv_img_set_src(ui_timeImage4, &ui_img_time_png);
    lv_obj_set_width(ui_timeImage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeImage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeImage4, -22);
    lv_obj_set_y(ui_timeImage4, 0);
    lv_obj_set_align(ui_timeImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeImage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_timeImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiImage4 = lv_img_create(ui_upsideContain4);
    lv_img_set_src(ui_wifiImage4, &ui_img_wifi__png);
    lv_obj_set_width(ui_wifiImage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiImage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiImage4, 333);
    lv_obj_set_y(ui_wifiImage4, 0);
    lv_obj_set_align(ui_wifiImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiImage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sideContain3 = lv_obj_create(ui_Container18);
    lv_obj_remove_style_all(ui_sideContain3);
    lv_obj_set_width(ui_sideContain3, 60);
    lv_obj_set_height(ui_sideContain3, 50);
    lv_obj_set_x(ui_sideContain3, -370);
    lv_obj_set_y(ui_sideContain3, -213);
    lv_obj_set_align(ui_sideContain3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sideContain3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sideContain3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sideContain3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sideContain3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sideContain3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sideContain3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_closeImgButton4 = lv_imgbtn_create(ui_sideContain3);
    lv_imgbtn_set_src(ui_closeImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_shutdown_png, NULL);
    lv_imgbtn_set_src(ui_closeImgButton4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_shutdown_png, NULL);
    lv_imgbtn_set_src(ui_closeImgButton4, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_closeImgButton4, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_closeImgButton4, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_closeImgButton4, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_closeImgButton4, 34);
    lv_obj_set_width(ui_closeImgButton4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_closeImgButton4, LV_ALIGN_CENTER);

    ui_Container33 = lv_obj_create(ui_Container18);
    lv_obj_remove_style_all(ui_Container33);
    lv_obj_set_width(ui_Container33, 735);
    lv_obj_set_height(ui_Container33, 85);
    lv_obj_set_x(ui_Container33, 29);
    lv_obj_set_y(ui_Container33, 193);
    lv_obj_set_align(ui_Container33, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container33, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container33, lv_color_hex(0xF8F4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stopButt2 = lv_imgbtn_create(ui_Container33);
    lv_imgbtn_set_src(ui_stopButt2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_stop_png, NULL);
    lv_imgbtn_set_src(ui_stopButt2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_start_png, NULL);
    lv_imgbtn_set_src(ui_stopButt2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_stopButt2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_stopButt2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_stopButt2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_stopButt2, 50);
    lv_obj_set_width(ui_stopButt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_stopButt2, -15);
    lv_obj_set_y(ui_stopButt2, 0);
    lv_obj_set_align(ui_stopButt2, LV_ALIGN_CENTER);

    ui_nextButt2 = lv_imgbtn_create(ui_Container33);
    lv_imgbtn_set_src(ui_nextButt2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_next1_png, NULL);
    lv_imgbtn_set_src(ui_nextButt2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_next2_png, NULL);
    lv_imgbtn_set_src(ui_nextButt2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextButt2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextButt2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextButt2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_nextButt2, 50);
    lv_obj_set_width(ui_nextButt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_nextButt2, 70);
    lv_obj_set_y(ui_nextButt2, 0);
    lv_obj_set_align(ui_nextButt2, LV_ALIGN_CENTER);

    ui_lastButt2 = lv_imgbtn_create(ui_Container33);
    lv_imgbtn_set_src(ui_lastButt2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_last2_png, NULL);
    lv_imgbtn_set_src(ui_lastButt2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1363945504, NULL);
    lv_imgbtn_set_src(ui_lastButt2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastButt2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastButt2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastButt2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_lastButt2, 50);
    lv_obj_set_width(ui_lastButt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_lastButt2, -100);
    lv_obj_set_y(ui_lastButt2, 0);
    lv_obj_set_align(ui_lastButt2, LV_ALIGN_CENTER);

    ui_Slider4 = lv_slider_create(ui_Container33);
    lv_slider_set_value(ui_Slider4, 80, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 150);
    lv_obj_set_height(ui_Slider4, 12);
    lv_obj_set_x(ui_Slider4, 250);
    lv_obj_set_y(ui_Slider4, 0);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_CENTER);


    ui_Image4 = lv_img_create(ui_Container33);
    lv_img_set_src(ui_Image4, &ui_img_soun2_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 150);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_soundLabel2 = lv_label_create(ui_Container33);
    lv_obj_set_width(ui_soundLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soundLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soundLabel2, 345);
    lv_obj_set_y(ui_soundLabel2, -1);
    lv_obj_set_align(ui_soundLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_soundLabel2, "80%");
    lv_obj_set_style_text_color(ui_soundLabel2, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_soundLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_videoText = lv_textarea_create(ui_Container33);
    lv_obj_set_width(ui_videoText, 191);
    lv_obj_set_height(ui_videoText, 70);
    lv_obj_set_x(ui_videoText, -259);
    lv_obj_set_y(ui_videoText, 0);
    lv_obj_set_align(ui_videoText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_videoText, "Video Information");
    lv_obj_set_style_text_color(ui_videoText, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_videoText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_videoText, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_videoText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_videoContain = lv_obj_create(ui_Container18);
    lv_obj_remove_style_all(ui_videoContain);
    lv_obj_set_width(ui_videoContain, 733);
    lv_obj_set_height(ui_videoContain, 330);
    lv_obj_set_x(ui_videoContain, 29);
    lv_obj_set_y(ui_videoContain, -20);
    lv_obj_set_align(ui_videoContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_videoContain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Container18);
    lv_obj_set_width(ui_Panel2, 738);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, 62);
    lv_obj_set_y(ui_Panel2, -84);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x080B19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeSlider = lv_slider_create(ui_Panel2);
    lv_slider_set_value(ui_timeSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_timeSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_timeSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_timeSlider, 620);
    lv_obj_set_height(ui_timeSlider, 10);
    lv_obj_set_x(ui_timeSlider, -10);
    lv_obj_set_y(ui_timeSlider, 0);
    lv_obj_set_align(ui_timeSlider, LV_ALIGN_BOTTOM_LEFT);


    ui_timeContainer = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_timeContainer);
    lv_obj_set_width(ui_timeContainer, 100);
    lv_obj_set_height(ui_timeContainer, 45);
    lv_obj_set_x(ui_timeContainer, 314);
    lv_obj_set_y(ui_timeContainer, -3);
    lv_obj_set_align(ui_timeContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sumtimeLabel = lv_label_create(ui_timeContainer);
    lv_obj_set_width(ui_sumtimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sumtimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sumtimeLabel, 25);
    lv_obj_set_y(ui_sumtimeLabel, 0);
    lv_obj_set_align(ui_sumtimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sumtimeLabel, "time");
    lv_obj_set_style_text_color(ui_sumtimeLabel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sumtimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowtimeLabel = lv_label_create(ui_timeContainer);
    lv_obj_set_width(ui_nowtimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nowtimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nowtimeLabel, -25);
    lv_obj_set_y(ui_nowtimeLabel, 0);
    lv_obj_set_align(ui_nowtimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nowtimeLabel, "time");
    lv_obj_set_style_text_color(ui_nowtimeLabel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nowtimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_timeContainer);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "/");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_mainFunBut3, ui_event_mainFunBut3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_houseFunBut3, ui_event_houseFunBut3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tipsFunBut3, ui_event_tipsFunBut3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_musicrFunBut3, ui_event_musicrFunBut3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sumspeakButt4, ui_event_sumspeakButt4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_closeImgButton4, ui_event_closeImgButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stopButt2, ui_event_stopButt2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_nextButt2, ui_event_nextButt2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lastButt2, ui_event_lastButt2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider4, ui_event_Slider4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_videoContain, ui_event_videoContain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeSlider, ui_event_timeSlider, LV_EVENT_ALL, NULL);

}
