// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_loginScreen
void ui_loginScreen_screen_init(void);
lv_obj_t * ui_loginScreen;
lv_obj_t * ui_loginWin;
lv_obj_t * ui_Container2;
lv_obj_t * ui_TextArea5;
lv_obj_t * ui_Container4;
void ui_event_loginButton(lv_event_t * e);
lv_obj_t * ui_loginButton;
lv_obj_t * ui_loginlable;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Container10;


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t * ui_mainScreen;
lv_obj_t * ui_Container1;
lv_obj_t * ui_leftsideContain1;
void ui_event_mainFunBut(lv_event_t * e);
lv_obj_t * ui_mainFunBut;
void ui_event_houseFunBut(lv_event_t * e);
lv_obj_t * ui_houseFunBut;
void ui_event_tipsFunBut(lv_event_t * e);
lv_obj_t * ui_tipsFunBut;
void ui_event_musicrFunBut(lv_event_t * e);
lv_obj_t * ui_musicrFunBut;
lv_obj_t * ui_Panel1;
void ui_event_sumspeakButt(lv_event_t * e);
lv_obj_t * ui_sumspeakButt;
lv_obj_t * ui_upsideContain1;
lv_obj_t * ui_signImage1;
lv_obj_t * ui_rightContain;
lv_obj_t * ui_time1;
lv_obj_t * ui_timeImage1;
lv_obj_t * ui_wifiImage1;
lv_obj_t * ui_sideContain;
void ui_event_closeImgButton1(lv_event_t * e);
lv_obj_t * ui_closeImgButton1;
void ui_event_enterImgButton1(lv_event_t * e);
lv_obj_t * ui_enterImgButton1;
void ui_event_speakImgButton1(lv_event_t * e);
lv_obj_t * ui_speakImgButton1;
lv_obj_t * ui_ansText;
void ui_event_speakText(lv_event_t * e);
lv_obj_t * ui_speakText;
lv_obj_t * ui_coreContain1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Image5;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;


// SCREEN: ui_houseScreen
void ui_houseScreen_screen_init(void);
lv_obj_t * ui_houseScreen;
lv_obj_t * ui_Container11;
lv_obj_t * ui_leftsideContain2;
void ui_event_mainFunBut1(lv_event_t * e);
lv_obj_t * ui_mainFunBut1;
void ui_event_houseFunBut1(lv_event_t * e);
lv_obj_t * ui_houseFunBut1;
void ui_event_tipsFunBut1(lv_event_t * e);
lv_obj_t * ui_tipsFunBut1;
void ui_event_musicrFunBut1(lv_event_t * e);
lv_obj_t * ui_musicrFunBut1;
lv_obj_t * ui_Panel10;
void ui_event_sumspeakButt2(lv_event_t * e);
lv_obj_t * ui_sumspeakButt2;
lv_obj_t * ui_upsideContain2;
lv_obj_t * ui_signImage2;
lv_obj_t * ui_rightContain1;
lv_obj_t * ui_time2;
lv_obj_t * ui_timeImage2;
lv_obj_t * ui_wifiImage2;
lv_obj_t * ui_sideContain1;
void ui_event_closeImgButton2(lv_event_t * e);
lv_obj_t * ui_closeImgButton2;
lv_obj_t * ui_envirContain;
lv_obj_t * ui_secureContain;
lv_obj_t * ui_Container19;
lv_obj_t * ui_TextArea1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_tempContain;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label5;
lv_obj_t * ui_tempText;
lv_obj_t * ui_humdContain;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Label8;
lv_obj_t * ui_humdText;
lv_obj_t * ui_electContain;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label4;
lv_obj_t * ui_electText;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_systemContain;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Container12;
void ui_event_therImgButt(lv_event_t * e);
lv_obj_t * ui_therImgButt;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Container5;
lv_obj_t * ui_intempText;
lv_obj_t * ui_Container13;
void ui_event_iceButt(lv_event_t * e);
lv_obj_t * ui_iceButt;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Container3;
void ui_event_iceArc(lv_event_t * e);
lv_obj_t * ui_iceArc;
lv_obj_t * ui_iceLabel;
lv_obj_t * ui_Container14;
void ui_event_airButt(lv_event_t * e);
lv_obj_t * ui_airButt;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Container15;
lv_obj_t * ui_airText;
lv_obj_t * ui_lightContain;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Container24;
void ui_event_ImgButton7(lv_event_t * e);
lv_obj_t * ui_ImgButton7;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label16;
void ui_event_Slider7(lv_event_t * e);
lv_obj_t * ui_Slider7;
lv_obj_t * ui_Label17;
lv_obj_t * ui_sliderLabel7;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Container16;
void ui_event_ImgButton2(lv_event_t * e);
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label19;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Label20;
lv_obj_t * ui_sliderLabel2;
lv_obj_t * ui_Container20;
lv_obj_t * ui_Container21;
void ui_event_ImgButton5(lv_event_t * e);
lv_obj_t * ui_ImgButton5;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
void ui_event_Slider5(lv_event_t * e);
lv_obj_t * ui_Slider5;
lv_obj_t * ui_Label23;
lv_obj_t * ui_sliderLabel5;
lv_obj_t * ui_Container22;
lv_obj_t * ui_lifeContain;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Container30;
void ui_event_ImgButton10(lv_event_t * e);
lv_obj_t * ui_ImgButton10;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Container23;
lv_obj_t * ui_TextArea12;
lv_obj_t * ui_Container25;
void ui_event_ImgButton6(lv_event_t * e);
lv_obj_t * ui_ImgButton6;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Container26;
lv_obj_t * ui_Container27;
void ui_event_ImgButton8(lv_event_t * e);
lv_obj_t * ui_ImgButton8;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Container28;


// SCREEN: ui_musicScreen
void ui_musicScreen_screen_init(void);
lv_obj_t * ui_musicScreen;
lv_obj_t * ui_Container17;
lv_obj_t * ui_leftsideContain3;
void ui_event_mainFunBut2(lv_event_t * e);
lv_obj_t * ui_mainFunBut2;
void ui_event_houseFunBut2(lv_event_t * e);
lv_obj_t * ui_houseFunBut2;
void ui_event_tipsFunBut2(lv_event_t * e);
lv_obj_t * ui_tipsFunBut2;
void ui_event_musicrFunBut2(lv_event_t * e);
lv_obj_t * ui_musicrFunBut2;
lv_obj_t * ui_Panel12;
void ui_event_sumspeakButt3(lv_event_t * e);
lv_obj_t * ui_sumspeakButt3;
lv_obj_t * ui_upsideContain3;
lv_obj_t * ui_signImage3;
lv_obj_t * ui_rightContain2;
lv_obj_t * ui_time3;
lv_obj_t * ui_timeImage3;
lv_obj_t * ui_wifiImage3;
lv_obj_t * ui_sideContain2;
void ui_event_closeImgButton3(lv_event_t * e);
lv_obj_t * ui_closeImgButton3;
lv_obj_t * ui_Container29;
lv_obj_t * ui_Container31;
void ui_event_stopButt(lv_event_t * e);
lv_obj_t * ui_stopButt;
void ui_event_nextButt(lv_event_t * e);
lv_obj_t * ui_nextButt;
void ui_event_lastButt(lv_event_t * e);
lv_obj_t * ui_lastButt;
lv_obj_t * ui_songerText;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_soundLabel;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_timeSlider2;
lv_obj_t * ui_timeContainer2;
lv_obj_t * ui_sumtimeLabel2;
lv_obj_t * ui_nowtimeLabel2;
lv_obj_t * ui_Label31;
void ui_event_videoContain2(lv_event_t * e);
lv_obj_t * ui_videoContain2;
lv_obj_t * ui_Panel9;
void ui_event_timeSlider3(lv_event_t * e);
lv_obj_t * ui_timeSlider3;
lv_obj_t * ui_timeContainer3;
lv_obj_t * ui_sumtimeLabel3;
lv_obj_t * ui_nowtimeLabel3;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_musiceCordImage;
lv_obj_t * ui_Image3;
lv_obj_t * ui_musicTextArea;


// SCREEN: ui_videoScreen
void ui_videoScreen_screen_init(void);
lv_obj_t * ui_videoScreen;
lv_obj_t * ui_Container18;
lv_obj_t * ui_leftsideContain4;
void ui_event_mainFunBut3(lv_event_t * e);
lv_obj_t * ui_mainFunBut3;
void ui_event_houseFunBut3(lv_event_t * e);
lv_obj_t * ui_houseFunBut3;
void ui_event_tipsFunBut3(lv_event_t * e);
lv_obj_t * ui_tipsFunBut3;
void ui_event_musicrFunBut3(lv_event_t * e);
lv_obj_t * ui_musicrFunBut3;
lv_obj_t * ui_Panel13;
void ui_event_sumspeakButt4(lv_event_t * e);
lv_obj_t * ui_sumspeakButt4;
lv_obj_t * ui_upsideContain4;
lv_obj_t * ui_signImage4;
lv_obj_t * ui_rightContain3;
lv_obj_t * ui_time4;
lv_obj_t * ui_timeImage4;
lv_obj_t * ui_wifiImage4;
lv_obj_t * ui_sideContain3;
void ui_event_closeImgButton4(lv_event_t * e);
lv_obj_t * ui_closeImgButton4;
lv_obj_t * ui_Container33;
void ui_event_stopButt2(lv_event_t * e);
lv_obj_t * ui_stopButt2;
void ui_event_nextButt2(lv_event_t * e);
lv_obj_t * ui_nextButt2;
void ui_event_lastButt2(lv_event_t * e);
lv_obj_t * ui_lastButt2;
void ui_event_Slider4(lv_event_t * e);
lv_obj_t * ui_Slider4;
lv_obj_t * ui_Image4;
lv_obj_t * ui_soundLabel2;
lv_obj_t * ui_videoText;
void ui_event_videoContain(lv_event_t * e);
lv_obj_t * ui_videoContain;
lv_obj_t * ui_Panel2;
void ui_event_timeSlider(lv_event_t * e);
lv_obj_t * ui_timeSlider;
lv_obj_t * ui_timeContainer;
lv_obj_t * ui_sumtimeLabel;
lv_obj_t * ui_nowtimeLabel;
lv_obj_t * ui_Label28;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_jarvis[1] = {&ui_img_jarvis3_png};
const lv_img_dsc_t * ui_imgset_last[1] = {&ui_img_last2_png};
const lv_img_dsc_t * ui_imgset_light[1] = {&ui_img_light1_png};
const lv_img_dsc_t * ui_imgset_line[1] = {&ui_img_line1_png};
const lv_img_dsc_t * ui_imgset_mp[1] = {&ui_img_mp4_png};
const lv_img_dsc_t * ui_imgset_music[1] = {&ui_img_music2_png};
const lv_img_dsc_t * ui_imgset_next[2] = {&ui_img_next1_png, &ui_img_next2_png};
const lv_img_dsc_t * ui_imgset_soun[1] = {&ui_img_soun2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_loginButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainScreen_screen_init);
    }
}
void ui_event_mainFunBut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainScreen_screen_init);
    }
}
void ui_event_houseFunBut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_houseScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 20, &ui_houseScreen_screen_init);
    }
}
void ui_event_tipsFunBut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_videoScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_videoScreen_screen_init);
    }
}
void ui_event_musicrFunBut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_musicScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_musicScreen_screen_init);
    }
}
void ui_event_sumspeakButt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        speak_fun(e);
    }
}
void ui_event_closeImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_loginScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_loginScreen_screen_init);
    }
}
void ui_event_enterImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        send_cmd_fun(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_speakImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        speak_fun(e);
    }
}
void ui_event_speakText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_speakText);
    }
}
void ui_event_mainFunBut1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainScreen_screen_init);
    }
}
void ui_event_houseFunBut1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_houseScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 20, &ui_houseScreen_screen_init);
    }
}
void ui_event_tipsFunBut1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_videoScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_videoScreen_screen_init);
    }
}
void ui_event_musicrFunBut1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_musicScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_musicScreen_screen_init);
    }
}
void ui_event_sumspeakButt2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        speak_fun(e);
    }
}
void ui_event_closeImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_loginScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_loginScreen_screen_init);
    }
}
void ui_event_therImgButt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        toggle_btn_nest(e);
    }
}
void ui_event_iceButt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        toggle_arc_switch(e);
    }
}
void ui_event_iceArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_arc_set_text_value(ui_iceLabel, target, "", "°C");
    }
}
void ui_event_airButt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        toggle_btn_air(e);
    }
}
void ui_event_ImgButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        toggle_slider_lock1(e);
    }
}
void ui_event_Slider7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_text_value(ui_sliderLabel7, target, "", "%");
    }
}
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        toggle_slider_lock2(e);
    }
}
void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_text_value(ui_sliderLabel2, target, "", "%");
    }
}
void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        toggle_slider_lock3(e);
    }
}
void ui_event_Slider5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_text_value(ui_sliderLabel5, target, "", "%");
    }
}
void ui_event_ImgButton10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        toggle_btn_reg(e);
    }
}
void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        toggle_btn_wash(e);
    }
}
void ui_event_ImgButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        toggle_btn_cur(e);
    }
}
void ui_event_mainFunBut2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainScreen_screen_init);
    }
}
void ui_event_houseFunBut2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_houseScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 20, &ui_houseScreen_screen_init);
    }
}
void ui_event_tipsFunBut2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_videoScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_videoScreen_screen_init);
    }
}
void ui_event_musicrFunBut2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_musicScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_musicScreen_screen_init);
    }
}
void ui_event_sumspeakButt3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        speak_fun(e);
    }
}
void ui_event_closeImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_loginScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_loginScreen_screen_init);
    }
}
void ui_event_stopButt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        start_stop_fun(e);
    }
}
void ui_event_nextButt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        next_music_fun(e);
    }
}
void ui_event_lastButt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        last_music_fun(e);
    }
}
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_text_value(ui_soundLabel, target, "", "%");
        volume_control_musice(e);
    }
}
void ui_event_videoContain2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_timeSlider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_VALUE_CHANGED || event_code == LV_EVENT_RELEASED) {
        sound_time_fun(e);
    }
}
void ui_event_mainFunBut3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainScreen_screen_init);
    }
}
void ui_event_houseFunBut3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_houseScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 20, &ui_houseScreen_screen_init);
    }
}
void ui_event_tipsFunBut3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_videoScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_videoScreen_screen_init);
    }
}
void ui_event_musicrFunBut3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_musicScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_musicScreen_screen_init);
    }
}
void ui_event_sumspeakButt4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        speak_fun(e);
    }
}
void ui_event_closeImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_loginScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_loginScreen_screen_init);
    }
}
void ui_event_stopButt2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        start_stop_video_fun(e);
    }
}
void ui_event_nextButt2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        next_video_fun(e);
    }
}
void ui_event_lastButt2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        last_video_fun(e);
    }
}
void ui_event_Slider4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_text_value(ui_soundLabel2, target, "", "%");
        volume_control_video(e);
    }
}
void ui_event_videoContain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_timeSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_VALUE_CHANGED || event_code == LV_EVENT_RELEASED) {
        video_time_fun(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_loginScreen_screen_init();
    ui_mainScreen_screen_init();
    ui_houseScreen_screen_init();
    ui_musicScreen_screen_init();
    ui_videoScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_loginScreen);
}
