// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_loginScreen
void ui_loginScreen_screen_init(void);
extern lv_obj_t * ui_loginScreen;
extern lv_obj_t * ui_loginWin;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_Container4;
void ui_event_loginButton(lv_event_t * e);
extern lv_obj_t * ui_loginButton;
extern lv_obj_t * ui_loginlable;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Container10;
// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_leftsideContain1;
void ui_event_mainFunBut(lv_event_t * e);
extern lv_obj_t * ui_mainFunBut;
void ui_event_houseFunBut(lv_event_t * e);
extern lv_obj_t * ui_houseFunBut;
void ui_event_tipsFunBut(lv_event_t * e);
extern lv_obj_t * ui_tipsFunBut;
void ui_event_musicrFunBut(lv_event_t * e);
extern lv_obj_t * ui_musicrFunBut;
extern lv_obj_t * ui_Panel1;
void ui_event_sumspeakButt(lv_event_t * e);
extern lv_obj_t * ui_sumspeakButt;
extern lv_obj_t * ui_upsideContain1;
extern lv_obj_t * ui_signImage1;
extern lv_obj_t * ui_rightContain;
extern lv_obj_t * ui_time1;
extern lv_obj_t * ui_timeImage1;
extern lv_obj_t * ui_wifiImage1;
extern lv_obj_t * ui_sideContain;
void ui_event_closeImgButton1(lv_event_t * e);
extern lv_obj_t * ui_closeImgButton1;
void ui_event_enterImgButton1(lv_event_t * e);
extern lv_obj_t * ui_enterImgButton1;
void ui_event_speakImgButton1(lv_event_t * e);
extern lv_obj_t * ui_speakImgButton1;
extern lv_obj_t * ui_ansText;
void ui_event_speakText(lv_event_t * e);
extern lv_obj_t * ui_speakText;
extern lv_obj_t * ui_coreContain1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image5;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
// SCREEN: ui_houseScreen
void ui_houseScreen_screen_init(void);
extern lv_obj_t * ui_houseScreen;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_leftsideContain2;
void ui_event_mainFunBut1(lv_event_t * e);
extern lv_obj_t * ui_mainFunBut1;
void ui_event_houseFunBut1(lv_event_t * e);
extern lv_obj_t * ui_houseFunBut1;
void ui_event_tipsFunBut1(lv_event_t * e);
extern lv_obj_t * ui_tipsFunBut1;
void ui_event_musicrFunBut1(lv_event_t * e);
extern lv_obj_t * ui_musicrFunBut1;
extern lv_obj_t * ui_Panel10;
void ui_event_sumspeakButt2(lv_event_t * e);
extern lv_obj_t * ui_sumspeakButt2;
extern lv_obj_t * ui_upsideContain2;
extern lv_obj_t * ui_signImage2;
extern lv_obj_t * ui_rightContain1;
extern lv_obj_t * ui_time2;
extern lv_obj_t * ui_timeImage2;
extern lv_obj_t * ui_wifiImage2;
extern lv_obj_t * ui_sideContain1;
void ui_event_closeImgButton2(lv_event_t * e);
extern lv_obj_t * ui_closeImgButton2;
extern lv_obj_t * ui_envirContain;
extern lv_obj_t * ui_secureContain;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_tempContain;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_tempText;
extern lv_obj_t * ui_humdContain;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_humdText;
extern lv_obj_t * ui_electContain;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_electText;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_systemContain;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container12;
void ui_event_therImgButt(lv_event_t * e);
extern lv_obj_t * ui_therImgButt;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_intempText;
extern lv_obj_t * ui_Container13;
void ui_event_iceButt(lv_event_t * e);
extern lv_obj_t * ui_iceButt;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Container3;
void ui_event_iceArc(lv_event_t * e);
extern lv_obj_t * ui_iceArc;
extern lv_obj_t * ui_iceLabel;
extern lv_obj_t * ui_Container14;
void ui_event_airButt(lv_event_t * e);
extern lv_obj_t * ui_airButt;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_airText;
extern lv_obj_t * ui_lightContain;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Container24;
void ui_event_ImgButton7(lv_event_t * e);
extern lv_obj_t * ui_ImgButton7;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label16;
void ui_event_Slider7(lv_event_t * e);
extern lv_obj_t * ui_Slider7;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_sliderLabel7;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container16;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_sliderLabel2;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_Container21;
void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
void ui_event_Slider5(lv_event_t * e);
extern lv_obj_t * ui_Slider5;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_sliderLabel5;
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_lifeContain;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Container30;
void ui_event_ImgButton10(lv_event_t * e);
extern lv_obj_t * ui_ImgButton10;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_TextArea12;
extern lv_obj_t * ui_Container25;
void ui_event_ImgButton6(lv_event_t * e);
extern lv_obj_t * ui_ImgButton6;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Container26;
extern lv_obj_t * ui_Container27;
void ui_event_ImgButton8(lv_event_t * e);
extern lv_obj_t * ui_ImgButton8;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Container28;
// SCREEN: ui_musicScreen
void ui_musicScreen_screen_init(void);
extern lv_obj_t * ui_musicScreen;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_leftsideContain3;
void ui_event_mainFunBut2(lv_event_t * e);
extern lv_obj_t * ui_mainFunBut2;
void ui_event_houseFunBut2(lv_event_t * e);
extern lv_obj_t * ui_houseFunBut2;
void ui_event_tipsFunBut2(lv_event_t * e);
extern lv_obj_t * ui_tipsFunBut2;
void ui_event_musicrFunBut2(lv_event_t * e);
extern lv_obj_t * ui_musicrFunBut2;
extern lv_obj_t * ui_Panel12;
void ui_event_sumspeakButt3(lv_event_t * e);
extern lv_obj_t * ui_sumspeakButt3;
extern lv_obj_t * ui_upsideContain3;
extern lv_obj_t * ui_signImage3;
extern lv_obj_t * ui_rightContain2;
extern lv_obj_t * ui_time3;
extern lv_obj_t * ui_timeImage3;
extern lv_obj_t * ui_wifiImage3;
extern lv_obj_t * ui_sideContain2;
void ui_event_closeImgButton3(lv_event_t * e);
extern lv_obj_t * ui_closeImgButton3;
extern lv_obj_t * ui_Container29;
extern lv_obj_t * ui_Container31;
void ui_event_stopButt(lv_event_t * e);
extern lv_obj_t * ui_stopButt;
void ui_event_nextButt(lv_event_t * e);
extern lv_obj_t * ui_nextButt;
void ui_event_lastButt(lv_event_t * e);
extern lv_obj_t * ui_lastButt;
extern lv_obj_t * ui_songerText;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_soundLabel;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_timeSlider2;
extern lv_obj_t * ui_timeContainer2;
extern lv_obj_t * ui_sumtimeLabel2;
extern lv_obj_t * ui_nowtimeLabel2;
extern lv_obj_t * ui_Label31;
void ui_event_videoContain2(lv_event_t * e);
extern lv_obj_t * ui_videoContain2;
extern lv_obj_t * ui_Panel9;
void ui_event_timeSlider3(lv_event_t * e);
extern lv_obj_t * ui_timeSlider3;
extern lv_obj_t * ui_timeContainer3;
extern lv_obj_t * ui_sumtimeLabel3;
extern lv_obj_t * ui_nowtimeLabel3;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_musiceCordImage;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_musicTextArea;
// SCREEN: ui_videoScreen
void ui_videoScreen_screen_init(void);
extern lv_obj_t * ui_videoScreen;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_leftsideContain4;
void ui_event_mainFunBut3(lv_event_t * e);
extern lv_obj_t * ui_mainFunBut3;
void ui_event_houseFunBut3(lv_event_t * e);
extern lv_obj_t * ui_houseFunBut3;
void ui_event_tipsFunBut3(lv_event_t * e);
extern lv_obj_t * ui_tipsFunBut3;
void ui_event_musicrFunBut3(lv_event_t * e);
extern lv_obj_t * ui_musicrFunBut3;
extern lv_obj_t * ui_Panel13;
void ui_event_sumspeakButt4(lv_event_t * e);
extern lv_obj_t * ui_sumspeakButt4;
extern lv_obj_t * ui_upsideContain4;
extern lv_obj_t * ui_signImage4;
extern lv_obj_t * ui_rightContain3;
extern lv_obj_t * ui_time4;
extern lv_obj_t * ui_timeImage4;
extern lv_obj_t * ui_wifiImage4;
extern lv_obj_t * ui_sideContain3;
void ui_event_closeImgButton4(lv_event_t * e);
extern lv_obj_t * ui_closeImgButton4;
extern lv_obj_t * ui_Container33;
void ui_event_stopButt2(lv_event_t * e);
extern lv_obj_t * ui_stopButt2;
void ui_event_nextButt2(lv_event_t * e);
extern lv_obj_t * ui_nextButt2;
void ui_event_lastButt2(lv_event_t * e);
extern lv_obj_t * ui_lastButt2;
void ui_event_Slider4(lv_event_t * e);
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_soundLabel2;
extern lv_obj_t * ui_videoText;
void ui_event_videoContain(lv_event_t * e);
extern lv_obj_t * ui_videoContain;
extern lv_obj_t * ui_Panel2;
void ui_event_timeSlider(lv_event_t * e);
extern lv_obj_t * ui_timeSlider;
extern lv_obj_t * ui_timeContainer;
extern lv_obj_t * ui_sumtimeLabel;
extern lv_obj_t * ui_nowtimeLabel;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_ironman_png);    // assets/ironman.png
LV_IMG_DECLARE(ui_img_mainfunct_png);    // assets/mainFunct.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/home.png
LV_IMG_DECLARE(ui_img_video_png);    // assets/video.png
LV_IMG_DECLARE(ui_img_music2_png);    // assets/music2.png
LV_IMG_DECLARE(ui_img_speak_png);    // assets/speak.png
LV_IMG_DECLARE(ui_img_jarvis3_png);    // assets/Jarvis3.png
LV_IMG_DECLARE(ui_img_time_png);    // assets/time.png
LV_IMG_DECLARE(ui_img_wifi__png);    // assets/WIFI .png
LV_IMG_DECLARE(ui_img_shutdown_png);    // assets/shutdown.png
LV_IMG_DECLARE(ui_img_fly_png);    // assets/fly.png
LV_IMG_DECLARE(ui_img_core_png);    // assets/core.png
LV_IMG_DECLARE(ui_img_temp_png);    // assets/temp.png
LV_IMG_DECLARE(ui_img_humd_png);    // assets/humd.png
LV_IMG_DECLARE(ui_img_light1_png);    // assets/light1.png
LV_IMG_DECLARE(ui_img_closenest_png);    // assets/closenest.png
LV_IMG_DECLARE(ui_img_opennest_png);    // assets/opennest.png
LV_IMG_DECLARE(ui_img_openice_png);    // assets/openice.png
LV_IMG_DECLARE(ui_img_closelig_png);    // assets/closelig.png
LV_IMG_DECLARE(ui_img_closeice_png);    // assets/closeice.png
LV_IMG_DECLARE(ui_img_closeclean_png);    // assets/closeclean.png
LV_IMG_DECLARE(ui_img_openclean_png);    // assets/openclean.png
LV_IMG_DECLARE(ui_img_openlig_png);    // assets/openlig.png
LV_IMG_DECLARE(ui_img_closereg_png);    // assets/closereg.png
LV_IMG_DECLARE(ui_img_openreg_png);    // assets/openreg.png
LV_IMG_DECLARE(ui_img_closewash_png);    // assets/closewash.png
LV_IMG_DECLARE(ui_img_openwash_png);    // assets/openwash.png
LV_IMG_DECLARE(ui_img_closecur_png);    // assets/closecur.png
LV_IMG_DECLARE(ui_img_opencur_png);    // assets/opencur.png
LV_IMG_DECLARE(ui_img_stop_png);    // assets/stop.png
LV_IMG_DECLARE(ui_img_start_png);    // assets/start.png
LV_IMG_DECLARE(ui_img_next1_png);    // assets/next1.png
LV_IMG_DECLARE(ui_img_next2_png);    // assets/next2.png
LV_IMG_DECLARE(ui_img_last2_png);    // assets/last2.png
LV_IMG_DECLARE(ui_img_1363945504);    // assets/last1 (1).png
LV_IMG_DECLARE(ui_img_soun2_png);    // assets/soun2.png
LV_IMG_DECLARE(ui_img_line_png);    // assets/line.png
LV_IMG_DECLARE(ui_img_line1_png);    // assets/line1.png
LV_IMG_DECLARE(ui_img_mp4_png);    // assets/mp4.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
