// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void send_cmd_fun(lv_event_t * e)
{
	// Your code here
}

void toggle_btn_nest(lv_event_t * e)
{
	// Your code here
}

void toggle_arc_switch(lv_event_t * e)
{
	// Your code here
}

void toggle_btn_air(lv_event_t * e)
{
	// Your code here
}

void toggle_slider_lock1(lv_event_t * e)
{
	// Your code here
}

void toggle_slider_lock2(lv_event_t * e)
{
	// Your code here
}

void toggle_slider_lock3(lv_event_t * e)
{
	// Your code here
}

void toggle_btn_reg(lv_event_t * e)
{
	// Your code here
}

void toggle_btn_wash(lv_event_t * e)
{
	// Your code here
}

void toggle_btn_cur(lv_event_t * e)
{
	// Your code here
}

void start_sto_fun(lv_event_t * e)
{
	// Your code here
}

void next_music_fun(lv_event_t * e)
{
	// Your code here
}

void last_music_fun(lv_event_t * e)
{
	// Your code here
}

void volume_control_musice(lv_event_t * e)
{
	// Your code here
}

void sound_time_fun(lv_event_t * e)
{
	// Your code here
}

void start_stop_video_fun(lv_event_t * e)
{
	// Your code here
}

void next_video_fun(lv_event_t * e)
{
	// Your code here
}

void last_video_fun(lv_event_t * e)
{
	// Your code here
}

void volume_control_video(lv_event_t * e)
{
	// Your code here
}

void video_time_fun(lv_event_t * e)
{
	// Your code here
}
